[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "a4234ace72112ce0cb8b7f08e53c1d437655e050"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "49bbad76e9cc9d570c5ff34cf23f846247fd5220e12be2752b9080801855bcbf"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "0eeed9f4aff066aae40b12c52e2866c114168dae"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "7a15019aaae7c1181120fdab80a0d23e6842d897f0c5d316b720929870ffa3d3"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "0a582183076cc13058646f852b6624a21ec19a8c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "098bebcd8798d14669d15f784afc9adddc2164fe3381e5481b8fed941a610395"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "2933c83775940414cc9e6aa86d6a89bfff3baa85"
libgfortran_version = "3.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "840948ebd4e0e9dbff372534015b3f9353c32d91bfba7b4272873299a044d269"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "f5ef21a7687106cbedbdafadc5f38aa10458b300"
libgfortran_version = "4.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "969f68b38cbd37767a9d1201c3b4919f34a0d08fe26ca802d01192068810bd59"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "95b31686ca79985854eeb7c49c880c35210f28a8"
libgfortran_version = "5.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "186bc2c1ff56a1b73d0dbf1b84ef0a3a2088e42a4b2f17e8724f8e1eb53fec05"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "02891b2b54dc3a1ec492dbf00c1a5198a56461c2"
libgfortran_version = "3.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "2c7fa7e8f1b511dfec04cdb08e0afeec55afa4f073062605b4ad56a360594216"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "7a2abfe542379b45870ee8344725b7719349ee19"
libgfortran_version = "4.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "5c192a5c8b7a5a9d6aff1a66027e18f486582e12f28ef0e9eb08428e482a607a"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "cbe5ee025ea81f2830bb389f4bb9723fcf5c8c64"
libgfortran_version = "5.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "288460b81dd0f0b26e60967966075d6e35540fe19488fff059c777545b59232b"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "3c019fa9b74b90cdb6cbd3ebaaad3316a1696b51"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "ecf1fa3dfaf7e6a9e7132f42c9b24c2b334407a237531b1f8459311bbf4ab98c"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "f4074dade3379bd092eff134abec52bbe1bf6e3c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "ae1b49e185f01ff555c1b7b887977db7fefb4373e767a65bc8788a179ede0327"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "696988fb64e5d33211f4711ece4ae0b3956bfadc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "d9ef3433b6c77c3627cbeb55d536ccc84bcbb8cb736deea645113d281ad5a028"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "e8d22dc865b3b0d4d9e61a9f5d0151394322271f"
libgfortran_version = "3.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "6e5c35cbda8c551598a1fb2dee0b442ce9e84b2eda8d864e9e7ce18c0ff9eb73"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "70418dc733e5b5aa848edb3067b8d5cdf03f635a"
libgfortran_version = "4.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "cf830f0b73badc7a2488a42466b3695d4283a4a44a68c69686c31d858f52b3cf"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "eec2db6b9e7b8916020bb1097a09ef00288d6580"
libgfortran_version = "5.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "3048e32951507a37f6a2858c65a3ba842fff34ab60b224d684cb24a71132e099"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.0+0/NetCDFF.v4.6.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
