[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "cc5bcae8a69c3ce389138998db5881315cfb20bb"
libgfortran_version = "5.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "f4fa81cd99191bc9e495409a3c5a84a55d2c1766e3d5971ad3381b6ff5317185"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "93082cbb1288266f246913b95daeef7bd2b5a39e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "93443ebaccda559794f5b8cfe27aa065dd4e8621e5477b23dc44d56566d2f64a"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "c312426e2c191559047903f807f425557a609153"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "4f24d6eef805e8074f7647afc71dc53b7732de008839a6764b05d72964c4c053"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "41020e97e1d90a107acf51032c26b07fa3ef67eb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "7e2d1d248c875cae8515e6029130dd20ef490b92afbea99004695b0f586df550"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "6d96d0f943cf027ee10d53ca46e61020a82c5a73"
libgfortran_version = "3.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "d63cd83e2c51ba37020d64fd4fd63f3893f2840b11bbf6200e26593a28ff4f2c"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "fdb78a5d7c6646e6b9cc158362bb004fd8c0f4fe"
libgfortran_version = "4.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "7172b3f5454feadc8082f3d439b3e27346781f4cfa1d42b2a60905478671d512"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "a079902371abbedcde1db0de7611827b0f1edbc1"
libgfortran_version = "5.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "72806d381992c44aee69f557387a7a70b619ad3f70e3d323d80bc0c34654306b"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "a8e11c1c9dd89112bb637caa1c9b5e055029b119"
libgfortran_version = "3.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "1e7406513a70838935aff86272bfaa380fd923e2bbda4e5da9c203eb09a1ca66"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "7bab1ef6fe7f76a3f3716a8bdfa236b03e087dc2"
libgfortran_version = "4.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "ff6528e23fbd32763940eed999978ba3fd5105c6925dc598a2d4f29795ea186b"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "03e43efe74f14d42ebce1648f46a0b1301b919d1"
libgfortran_version = "5.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "da219223e49a1591c6faac307ef4b73dc15f2733041f621cb7680e500269937a"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "0fcaad4e18f77d32334eb5c8689f95ddc9e75860"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "cc530c906bc6d925d30d7ec3f8b30abd6936a988901d00e232e4c941dec8f982"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "2e72fdb10a99479dead14a19a0dde07f7a32b559"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "9ebf9b0094b20e0447c540630eaa872e20c3116743cbce2c739cd6ad06ec35db"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "b36337aabfec6160cdab566b9676c54c71fbeac0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "05f03d9482c1200ae6469788e75538a21b949551c8a4003f9f37b38a67553c7a"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "b47379a6c836662d12773cd7f7f2f8654000866e"
libgfortran_version = "3.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "c96bb5d103a3e40c908bead77a4b383b41dbb36800616d0b25514a21512e20a9"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "a004c3d1712a4ee5a82ad1019b001f5da1e89660"
libgfortran_version = "4.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "21b32eca1f97f3b44e2c0ef4d02e83e2d10f9ed986cbdf96877e97f035d49898"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "c972b96a4f2d0a9ed58c1453984243b5953a7fbd"
libgfortran_version = "5.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "4f479ac6d9d2bd564c06c659809056cc1e98d666e51dd860349b532a7141b13d"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.1+0/NetCDFF.v4.6.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
