[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "1178393174d1728229c9e21d4d2c01fd349a9bcd"
libgfortran_version = "5.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "12c0a56d1279c3ec83e021b570264aacd09d121b478527cae5f932451926619a"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.aarch64-apple-darwin-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "c07aff1be13237c15388fc184378cad284fae1b9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "def59101eb49b0bd2866a44b58067371a0de28ab7c4311e3457805f1f2374571"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.aarch64-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "7c9aaf8af8dbcbeca5480ed7ac9ea0e2042652e6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "e61083cd83ccc2cd8685bf59325f86e945aa041154806006db015a85dfe52e14"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.aarch64-linux-musl-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "9035df0258b994fcf816c17be1b11622a47a610c"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[NetCDFF.download]]
    sha256 = "d3623f7e70759271cef6f0608cc5af139b2f93209d92a0682fb9fc968edbf9cb"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3dd8de08bafe8d40680074eac53009c19ec3857c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "cd5d0482f2f1cad493296eedfabe7ed419d0d7274ea3f4c322079a860a736579"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ddacd43af9be11b515924a0a14c4912e5d2203d4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "083d246db9df6c55d3ec19d10ff2cda0619a0a43083f7553409bc08ec3e7e5e4"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "06727aa94e953bbe34a7cbfcc4f1ff79e5057bf2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "7c8c4dc9697966f1f7dcaa9d423658e3e028fbb8fac14c0b3508041fea90d4bb"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d276888e3d78ad1932da82572f8b4b18a9f58f28"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "fdd289e3132b3427499e370667a94e7ec1ccccfec23fe9a8d993ec2511391e0f"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "1d5d656298697973fd36bb89ad49d90417867816"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "ce7d1061ed1c37d18e9744e21d39ee8ed40bc6a70d626911955c35d7366468d3"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.i686-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "9aa4349d948c91caff9edd33d01b4c25e1eec921"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "eae8ec7a63c4490310f7f310c05d24fb1c5346d985b76245de90ff2bd86b351c"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.i686-linux-musl-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "bd4bf77fb23d9cd91cf5a2083c09abfc6c4eee6a"
libgfortran_version = "5.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "ad7295fbacd19d24d1ffa9bcf5bf08d6018e1eb54d5baebc2e763c14d7ee6d57"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.i686-w64-mingw32-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "powerpc64le"
git-tree-sha1 = "a51d2fdcb0a44f4220585c717ea940fdddc1979e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "a7e16fb2a08d5f775a7decf81e8c2f0b5f482930f3902f0690c322b20efd3adb"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "riscv64"
git-tree-sha1 = "47c69faa20e7244b78a58f6e8843ebdb170b584c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "8794f44a003dd8007cbc7b6733b0b8475bdbe4ec0f5da5b0f52c4c1b5e3aa6a8"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.riscv64-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "85b8bd7189a754a4a28b6cb4da181df002a775a2"
libgfortran_version = "5.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "f4e98b6d1eab4396ead648f30968f59c17a90c36a44d784327dc8fb1a1b09e70"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.x86_64-apple-darwin-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "5ccc9002a614e9f86c1da74a8cabba7a9aa242f4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "cedfc0eb79f9adc48d456e6776d7caef6fa5af8532bdb027dc11e2a808dbfb2d"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.x86_64-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "d5fe032c918a1d2b8ade8eb4272e8e9c168280e5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "3637979a117f80be7ff5b26f12488405a4072accbca1b8a01bb5e7baf3354746"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.x86_64-linux-musl-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "9a83674b55a879d0b878dde8ef3a7df6cb72538a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[NetCDFF.download]]
    sha256 = "f5abbb0e9256ca1a7af60ea0673f586f22c39fccea017e13a4108ac5870aa26e"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "3083606faf7d6dd71bde7d8e63a693ef14611cab"
libgfortran_version = "5.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "b1d1e2a9650198bd26d9a5429099278b27822d5bddbff2e07c2889259220f895"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.4+0/NetCDFF.v4.6.4.x86_64-w64-mingw32-libgfortran5.tar.gz"
