[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "81083c6fa347cdb4f2106b6c127b2c957e629888"
libgfortran_version = "5.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "e262339f9bf58de8a24af8a28e9642ae52fdaa260c1a8adce06025f196057d7c"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "bc5664923cb9e543ad3ec4a810d997ace1562c8c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "1953b61e5a64169ca266957199b53e3b186d055133e703e76abae2128220ffdc"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "79f6b0b2419ecf1ee7ed5412a32407f92a0b0aed"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "36000b3926d073ff3cfc1bd83c28e225a1360837b9a8297c38d9bc9e8e015e81"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "5801c8a950a69b03ea3402fdad4a197722846f71"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "a93c140dd0dba1af1827d1d789bf5bb94288ceb1cf4cb2f66ae9e641f7ad3855"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "b19d7a00691cfae7f59d37911d5db023ab5ec05c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "7133258033e2fc4107688e5b2d1de084096745a2c55878a61da57d43a137b689"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "867545bfe4c6ee01640564187373211a4f6c7a6a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "315278ce1e8e2ea7cf4d610b93f8bf7652ad87a37ffeedf94d89c99bcf73ae9d"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "e808d6f658dfde76e9f63d7d32b2de8333f7b68c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "12b5d7d94b51682a3ff4adb253f968b333254e4f6da279efa290b60a6cb98ba2"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "aarch64"
git-tree-sha1 = "22fbc4f5dd3da95e7774849f8736d6455fd10742"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[NetCDFF.download]]
    sha256 = "fd2d9a84def9aeb7006ba04f5bf423e9ac83ba49c3a9ebee5368f9b7c880d2ee"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3415229101b1114f27c4e92c07a7b3c9958a7b0d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "924ab1186f313c36248300474ceff3f856478409c208b4c7dc43483b203d602a"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8bdce051a6e9b86e9bb85774719a995671bacd19"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "ab0efa7c45a0e05fb511b9bf33da6b85bb28b0ca2be969dd0a25fcb6f2557046"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f39bdb5d0dc7bf57bd7f33b086c4e711d261d0d0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "e7025f3b303e1d02836410441ec6e8e9fa70a279ad090f980c368362a09144b4"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ef34d6477bfea5de4f26a708f6419771d409d049"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "02577f63d1136befbc00958e95a24643e56b9a3ea1806eee8292dac86b1a18ea"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6acded768093838ef9bd44a42ae96624b6be01dc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "b620c7f9ee58eb1191833d86c1de34b9d1ea5110c4b7774048e17b4a702c4ceb"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cf33231023f772270030eb119e4b4ae0f89e92b9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "d9ffb40e9dce9d566b428d14c7668675778421c53f91d265b2d4fb93f6c27ccb"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6dc55255896985738727974fe65c232b6a9410f4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "2bbca601fad05ac741b69544043a9caf0b5d164c06757174c4b71d3496121047"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "73b1de05c1341573a3e6ceda8979b7e6efae7fd3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "81bae813bd782a8987142c695a602c272b627d8e639cbfe51f3bdb94d5895c52"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b29c701c95928dcc1fc68511dc25c3de4e5e5a24"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "f1650b9efc5e32af9a8115584bfce410d7f12b4f63ec4a66b96aadb0940bec66"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "218de773df9457ac30cb6a3b8f18dcd403e0635a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "52f0590d88fc8c61eb57faed4935049793a15c88315d233de2732de1fb5731f8"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fee4af9685678b37fc01a23f342a6286f7e680fc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "e3c21b97d0ec0b9ea89b95aa3361935ccc3cb7168af1e7fcc07e0059c29fe535"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0506e626ec92d74314177f660eb709f288082c6d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "7563487cc9d137af7af594895a500f4070a2910d0787bbee9bf495bada305ae5"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "ec04a4a59f2e293a345c2fe38c4fc1d04ffababb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "089bccd7d3d9c35c9d879fc6cbcaa09f889993043faeab8010968a2ecf2f62b8"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.i686-linux-gnu-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "b4cce4a0de5396fbe2baa44bb6bd2cd9bf99bef7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "6699cdf3ea5ef86d49dcd958fecb13e0f2a14bda943deea97f20760a6abe4661"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.i686-linux-gnu-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "4bb67e73498084f94eba6fad85d41885adebbf63"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "b5db09109574e9201804292cb1726887490a5717d81c1b8c64e240e49a2e7714"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.i686-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "93799365ce01fc8616b34dca5fb2b96dd3dd9ce6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "634cd81390757052cb3c6296fac0bf0fcf2e6690a41f2c658ebb2f2b4cd71b38"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.i686-linux-musl-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "41eb7d25ed9ea697f0314a3a1a50986d85de4efb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "d85ca20f7454c20102f49eca2e7897943a415a0fdfa82c013e22b35cc70b0b6e"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.i686-linux-musl-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "6d93a643ab76cadc52fd3c46116c4a3fd186ae6a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "6cff686a28d84f8d65059a666dbee90f004d9d672de3b60a0033ac57c53426c8"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.i686-linux-musl-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "6f1af0fc104d8d3e553e1b199410d1ba93b2788a"
libgfortran_version = "3.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "39ca9f61df994bf00138379cfe8ab0c63464900cc93ebe47b2790e09082b7d97"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "5bce4e58e686a5178537b4fd2b8ef0507447181f"
libgfortran_version = "4.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "e0064833727f8b00659c1361aa80439b14fff728eaddffb265a620763df32823"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "i686"
git-tree-sha1 = "4e68c028a280205c79ee26f42d3e2d257a10395e"
libgfortran_version = "5.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "2a223cf99c65b875f1015a96d974fc68740fdb5e5b4f0b22fcbc886cc60d57dd"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "powerpc64le"
git-tree-sha1 = "5ccd642e58d3a1462adc6c466c2b55ca3e727591"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "ca95601976884c854054ff8ff608d70bcfcacb68f23012eb66e4ed4dcf4c43a9"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "powerpc64le"
git-tree-sha1 = "456871a02762292f2c6736bbe0e798781bf00089"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "e6b8237149cbd3dd36567974369202a5b4fa172546c7ac566777610efccb016c"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "powerpc64le"
git-tree-sha1 = "c7ad763536fa6d812ddac4c3cc1ced5498f3907d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "36f22f92780795500c552cf8b5c2a9f4c793a58d967f333279ada8ed66889410"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "riscv64"
git-tree-sha1 = "4f937d3f56f7ecf42d7fba596a2ef9032368a1ce"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "78507370171b14c1891099d91bbae865dcec916b9f958887330e8dbbcde89255"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.riscv64-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "ec15b770140a81ef7d4c56573bc095ba7623c66f"
libgfortran_version = "3.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "98be16de837c6d19bd2891a2de9468f0fe155eb4553ef15cfd1e4c8f27dd62c3"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "a2aaf7860a5eb4ca8e282f58e0acd80a98615841"
libgfortran_version = "4.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "6718ec2fce9205626ef6a20a2c9fa521c4965900472ae65ca24dd58d87682743"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "6a35efc53001065e2efc3a1642c84e0e4a8a091e"
libgfortran_version = "5.0.0"
os = "macos"

    [[NetCDFF.download]]
    sha256 = "abc44333b4d29816ce904e884fafdd7c192bdbe1b69804f5fbf2a5237a17d0ea"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "7ba9ebe86020c1d44474cd2f09f1e196a887924a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "b47fdcc897fbf97f6caa1a985458552eba8715ebb885c36129bb8bc9a7d87514"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "1cf9f541c72b5a0670012e991a17e1bc573e545b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "a09a46ecf95b3eda4beb2f16b437f1b099c96fafa023ba44c11ba11a509e5c3b"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "ac1df3f4e9c727aa403a44e22350c4c060b08fca"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "e0f61f371f986d5740c121d881376ef3ddb9f8cf8d0a32f7a5018225edc8cd17"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "2c8990003c7f98cca82da18ec16334f413869331"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "313a29f822566deb6f24cb1de2432ef55ac144a8af2b144acd88359ad5536523"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "318e0f79cd8e4f1fcc4a75c048c362b58f6c46af"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "2726dc1f70f8aa2869f8a92b5b22fd46b9fc7116faada163a6c5e7d3a2c25506"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "7dc91c4245ab139ab6db34a5b38b42d5e9d900e9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[NetCDFF.download]]
    sha256 = "655db03de988166440e807c72fe4dc2cfe33e3f29654f66191866cc73f58e832"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "6f82039a3244c20bd5689b81ef716dc57cc7f721"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[NetCDFF.download]]
    sha256 = "6bea5923f18c05646f8b0de24c5f95e65f5150febed7195092cf73ee2fe167c8"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "767889c3b5c16d0d16e5f84611196eee0171d696"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[NetCDFF.download]]
    sha256 = "b7e12b90662b0a3018c7b40ffea82a5ad40797a42ea5dddc1ece5ff899ca3422"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "d74b9ca8f1ef9bfde0bdb297e03d5c148d199c8a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[NetCDFF.download]]
    sha256 = "338458572f427cc1392e67d32da13782b988dffc8bfa1679de6ccb2203e03842"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "8868450bf320ba8864b3a0a9c44e99952ce30834"
libgfortran_version = "3.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "10a040151d4c9c8df5df4a85366937a5bdc034ddcd5d35c7703e3e178a53c0c7"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "f46e80094b2f5f910f04d3fbca62db61c036e1bb"
libgfortran_version = "4.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "a5205af70988faa8bd7e4d3cb533fe707b75f4531f4251fa214888a67d3812f5"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[NetCDFF]]
arch = "x86_64"
git-tree-sha1 = "ce4cccbe67cc2073077aa6f6cd6191b7dda849da"
libgfortran_version = "5.0.0"
os = "windows"

    [[NetCDFF.download]]
    sha256 = "007639591ba151d9d8e2ab5e9d84233dbddc6365ade1a32572838794ec5b349c"
    url = "https://github.com/JuliaBinaryWrappers/NetCDFF_jll.jl/releases/download/NetCDFF-v4.6.2+0/NetCDFF.v4.6.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
